version: "3.4"

services:
  backend:
    image: node:17-alpine
    container_name: backend
    build:
      context: backend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes: 
      - .db/:/data/db
    command:
      - --quiet